trigger: none
pr: none

schedules:
- cron: '0 * * * *'
  always: true
  branches:
    include:
    - master

pool: ubuntu-20.04

jobs:
- job: update
  steps:
  - checkout: self
    clean: true
    path: s
    persistCredentials: true
  - bash: |
      set -ex
      git config user.email 'sonicbld@microsoft.com'
      git config user.name 'Sonic Automation'
      rm -rf sonic-contributor-map
      git clone https://$(USER):$(PAT)@github.com/sonic-net/sonic-contributor-map

      ./sii_calculate.py

      git status | grep 'nothing to commit, working tree clean' && exit 0

      git status
      git diff

      git add .
      git commit -m "[automation] Update Sii Score by azure pipeline."
      git push origin HEAD:master
