trigger: none
pr: none

schedules:
- cron: '0 0 1 * *'
  always: true
  branches:
    include:
    - master

pool: sonicbld

jobs:
- job: update
  timeoutInMinutes: 600
  variables:
  - group: SONICBLD
  steps:
  - checkout: self
    clean: true
    path: s
  - bash: |
      set -x

      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      sudo apt update
      sudo apt install gh jq -y

      echo $TOKEN | gh auth login --with-token
      git remote remove sonicbld || true
      git remote add sonicbld https://mssonicbld:$TOKEN@github.com/mssonicbld/sonic-tsc/
      git fetch sonicbld
      git config user.email 'sonicbld@microsoft.com'
      git config user.name 'Sonic Automation'
    env:
      TOKEN: $(GH_TOKEN)
    displayName: setup env
  - bash: |
      set -x

      cd sii_hld
      ./dump_hld_data.sh
      git add dash_hld.csv sai_hld.csv sonic_hld.csv
      git commit -m "[data] Update HLD related data."
      git push sonicbld HEAD:refs/heads/data/hld -f
      re=$(gh pr create -R sonic-net/sonic-tsc -H mssonicbld:data/hld -B master -b '' -t "[data] Update HLD related data." 2>&1 || true)
      sleep 60
      git show HEAD --stat | grep '[0-9]* *deletions' -Eo || gh pr merge --auto $(echo $re | grep -Eo 'https://github.com/sonic-net/sonic-tsc/pull/[0-9]*') -s
      git reset HEAD~ --hard
      cd ..
    displayName: dump hld
    condition: ne(variables['SKIP_HLD'], 'y')

  - bash: |
      set -x

      cd sii_issue
      ./issues_dump.sh
      git add issues.json
      git commit -m "[data] Update issue related data."
      git push sonicbld HEAD:refs/heads/data/issue -f
      re=$(gh pr create -R sonic-net/sonic-tsc -H mssonicbld:data/issue -B master -b '' -t "[data] Update issue related data." 2>&1 || true)
      sleep 60
      add=$(git show HEAD --stat | grep '[0-9]* *insertions' -Eo | grep [0-9]* -Eo)
      del=$(git show HEAD --stat | grep '[0-9]* *deletions' -Eo | grep [0-9]* -Eo)
      (( add/del > 3 )) && (( del < 10 )) && gh pr merge --auto $(echo $re | grep -Eo 'https://github.com/sonic-net/sonic-tsc/pull/[0-9]*') -s
      git reset HEAD~ --hard
      cd ..
    displayName: dump issue
    condition: ne(variables['SKIP_ISSUE'], 'y')

  - bash: |
      set -x

      cd sii_testplan_hld
      ./generate_testplan_hld_data.sh
      git add sonic-mgmt_hld.csv
      git commit -m "[data] Update testplan HLD related data."
      git push sonicbld HEAD:refs/heads/data/testplan-hld -f
      re=$(gh pr create -R sonic-net/sonic-tsc -H mssonicbld:data/testplan-hld -B master -b '' -t "[data] Update testplan HLD related data." 2>&1 || true)
      sleep 60
      git show HEAD --stat | grep '[0-9]* *deletions' -Eo || gh pr merge --auto $(echo $re | grep -Eo 'https://github.com/sonic-net/sonic-tsc/pull/[0-9]*') -s
      git reset HEAD~ --hard
      cd ..
    displayName: dump test hld
    condition: ne(variables['SKIP_TESTHLD'], 'y')

  - bash: |
      set -x

      cd sii_pr_review
      for repo in $(cat repos)
      do
        current=$(date -I)
        year=${current:0:4}
        month=${current:5:2}
        (( month <=2 )) && year1=$(( $year -1 ))
        ./pr_dump.sh -y "$year1 $year" -r $repo
        ./pr_dump.sh -y "$year1 $year" -t reviews -r $repo
        repo_name=$(echo $repo | awk -F/ '{print$2}')
        ls $year1/$repo_name.*reviews.json &>/dev/null && ./parse_reviews.py $year1/$repo_name.*reviews.json
        ls $year/$repo_name.*reviews.json &>/dev/null && ./parse_reviews.py $year/$repo_name.*reviews.json
      done
      rm -rf $(find . -size -10c)
      git add $year1 $year
      git commit -m "[data] Update pr&review related data."
      git push sonicbld HEAD:refs/heads/data/pr -f
      re=$(gh pr create -R sonic-net/sonic-tsc -H mssonicbld:data/pr -B master -b '' -t "[data] Update pr&review related data." 2>&1 || true)
      sleep 60
      add=$(git show HEAD --stat | grep '[0-9]* *insertions' -Eo | grep [0-9]* -Eo)
      del=$(git show HEAD --stat | grep '[0-9]* *deletions' -Eo | grep [0-9]* -Eo)
      (( add/del > 3 )) && (( del < 10 )) && gh pr merge --auto $(echo $re | grep -Eo 'https://github.com/sonic-net/sonic-tsc/pull/[0-9]*') -s
      git reset HEAD~ --hard
      cd ..
    displayName: dump pr
    condition: ne(variables['SKIP_PR'], 'y')

  - bash: |
      set -x

      cd sii_test_pr_review
      current=$(date -I)
      year=${current:0:4}
      month=${current:5:2}
      (( month <=2 )) && year1=$(( $year -1 ))
      ./pr_dump.sh -y "$year1 $year"
      for file in $(find $year1 $year -name *.prs.json)
      do
        ./parse_prs.py $file
      done
      for file in $(find $year1 $year -name *.reviews.json)
      do
        ./parse_reviews.py $file
      done
      rm -rf $(find . -size -10c)
      git add $year1 $year
      git commit -m "[data] Update test pr&review related data."
      git push sonicbld HEAD:refs/heads/data/testpr -f
      re=$(gh pr create -R sonic-net/sonic-tsc -H mssonicbld:data/testpr -B master -b '' -t "[data] Update test pr&review related data." 2>&1 || true)
      sleep 60
      add=$(git show HEAD --stat | grep '[0-9]* *insertions' -Eo | grep [0-9]* -Eo)
      del=$(git show HEAD --stat | grep '[0-9]* *deletions' -Eo | grep [0-9]* -Eo)
      (( add/del > 3 )) && (( del < 10 )) && gh pr merge --auto $(echo $re | grep -Eo 'https://github.com/sonic-net/sonic-tsc/pull/[0-9]*') -s
      git reset HEAD~ --hard
      cd ..
    displayName: dump test pr
    condition: ne(variables['SKIP_TESTPR'], 'y')

